### ISSUE TITLE
Implicit declaration of function 'ftruncate'

### ISSUE THREAD

**Issue by imba-tjd** [imba-tjd/HDUHomeWork#3]
see this [code](https://github.com/imba-tjd/HDUHomeWork/blob/master/OperatingSystem/%E5%AE%9E%E9%AA%8C/%E5%AE%9E%E9%AA%8C%E4%B8%89(4)%EF%BC%9A%E5%85%B1%E4%BA%AB%E5%86%85%E5%AD%98%E8%BF%9B%E7%A8%8B%E9%80%9A%E4%BF%A1/sender.c#L16).
I have included `unistd.h` and `sys/types.h`, but it doesn't work.
However, my program did't report 'bus error' and crash.
![qq 20180629173139](https://user-images.githubusercontent.com/24759802/42085374-d000a48a-7bc2-11e8-9396-c96f3e37598d.png)
![qq 20180629152812](https://user-images.githubusercontent.com/24759802/42085380-d5e19b34-7bc2-11e8-839a-97abd71e9bb1.png)

**Comment by alrshdn** [comment]
I know this is so old, but there is no issue in answering it now.
Since you have enabled all warnings, you will have to compile with:
```
gcc -D_XOPEN_SOURCE=<version> ...
```
`<version>` has to be 500 or more for this specific feature (`ftruncate(...)`). This is shown in its manual page and in your screenshot.

You can find more explanation in `feature_test_macros(7)`; run the command:
```
man 7 feature_test_macros
```

Hope this help! Have a nice day.

**Comment by imba-tjd** [comment]
@alrshdn Thank you! I have no experence in developing Linux C program.

You are right. I tested it again and the warning disappers. ~~Accroding to the doc, it's because I'm using a newer glibc now.~~
Well, it seems that `/* Since glibc 2.12: */ _POSIX_C_SOURCE >= 200809L` means I need to use glibc >= 2.12 **and** define `_POSIX_C_SOURCE >= 200809L`. Althouth I tested `printf("%ld\n", _POSIX_C_SOURCE);` and it actually prints 200809 now.

I also tried to ask ChatGPT. After some instructions, it gives the solution of `#define _POSIX_C_SOURCE 200809L`, which is bigger than `200112L`. Students thesedays should have a better learning experience than I did.
